#runtime: python39
#entrypoint: gunicorn -b :$PORT application:app
#
#env_variables:
#  RF_CLASSIFIER_PATH: "RandomForest.pkl"
#
#automatic_scaling:
#  target_cpu_utilization: 0.65
#  min_instances: 1
#  max_instances: 10
#
#resources:
#  cpu: 1
#  memory_gb: 0.5
#  disk_size_gb: 10
runtime: python39
entrypoint: uvicorn application:app --host 0.0.0.0 --port $PORT
env_variables:
# Define your environment variables here, if any
# Example:
# VARIABLE_NAME: "value"

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

resources:
  cpu: 1
  memory_gb: 0.5
